### ISSUE TITLE
Concealed Display

### ISSUE THREAD

**Issue by chill78023** [mswlogo/V1Driver-Bugs#25] opened 2016-10-04 00:30 UTC
When I fire up V1 Driver with the app open, my mounted V1 remains dark and all warnings are on the concealed display. (This is correct behavior.)  When I background the app and switch to Waze, both my concealed display and V1 light up on alerts. (not the desired behavior)  Awesome app otherwise.  Thanks!

**Comment by mswlogo** [comment] 2016-10-07 05:04
This is FAD (Functions As Designed). The idea is you always need a Display of some sort. Either on the V1 or On the Phone (why have Arrows with no Display?). If you can see the Display on the phone, the V1 display is redundant. If you can't see the display on the phone then the V1 should be your display. I will offer an All Dark option in the future, but this was not that and why it's called "Auto Dark". If you read the Tool Tip it does exactly what you describe.

I will consider this a Feature Request for an "All Dark" option. But what is there is not incorrect behavior and what some users would want.

**Comment by mswlogo** [comment] 2016-10-07 05:06
Actually I'm closing this because there is already a bug called "All Dark" #23

**Closed as completed by mswlogo** 2016-10-07 05:06 UTC
Labels: enhancement, Priority 3
